mysql:
    username: username
    password: password
    addr: 127.0.0.1:3306
    db_name: test-db
    charset: utf8mb4
    parse_time: true #时间解析为go time.Time
    loc: Local
    max_idle_conns: 30 #最大空闲链接数
    max_open_conns: 100 #最大链接数
    conn_max_lifetime: 2 #链接最大生命周期, 单位:小时
    log_level: 2 #日志等级: 1silent, 2error, 3warn, 4info
redis:
    username: default
    password: "" #没有默认不填
    addr: 127.0.0.1:6379
    db: 0
    pool_size: 15 #连接池大小
    dial_timeout: 15 #拨号超时时间, 单位:秒
    read_timeout: 15 #读取超时时间, 单位:秒
    write_timeout: 15 #写入超时时间, 单位:秒
    idle_timeout: 15 #空闲链接超时时间, 单位:分钟
    max_idle_conns: 100 #最大空闲链接数
    min_idle_conns: 10 #最小空闲链接数
im_port: 8081 #im http和websocket运行端口
server_http_port: 8080 #中心服务器 http web服务端口
server_tcp_addr: 127.0.0.1:8085 #中心服务器 tcp 地址
environment: release #运行环境: debug, test, release
log_level: 2 #日志等级: -1-5 等级递增
jwt:
    issuer: example.com #签发者
    subject: user@example.com #主题
    audience: #接收者
        - example.com
    private_key: o98%C!YJHky=^_ZGRocrf #私钥
retries_times: 30 #tcp重连最大尝试次数 0-255
oss:
    prefix: "" #oss 前缀
    txt_name: "" #下载文件依赖文件
    switch: false #true远程加载, false本地加载